#!/bin/bash
echo "Configurar servicio LDAP:"

# CONTRASEÑA: 123


# Ejemplos estructura LDAP
#dn: cn=John Smith, ou=st, o=um, c=es		# Añade el cn en la ruta ou+o+c
#changetype: add				# Esto indica que la operacion es add
#objectclass: inetOrgPerson			# Se esta añadiendo un inetOrgPerson, es decir, que Jhon Smith hereda de inetOrgPerson (con sus atributos)
#objectclass: simpleSecurityObject		# Idem
#sn: Smith
#gn: John
#gn: Johnny
#userPassword: 1234

#dn: cn=Linus Torvalds, ou=st, o=um, c=es	# Se va ha modificar una entrada
#changetype: modify
#add: mail					# añadiendo un atributo
#mail: torvalds@klaava.Helsinki.FI
#-
#replace: mobile				# y modificando este atributo
#mobile: 698754321


# Habilitar base de datos tipo bdb
ldapmodify -Y EXTERNAL -H ldapi:/// -f archivo/loadDBD.ldif

# Importamos primero una clase que vamos a usar
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/inetorgperson.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/core.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/nis.ldif

# cremos la nueva
ldapadd -Y EXTERNAL -H ldapi:/// -f archivo/stSchema.ldif

# Configuracion de la base de datos
ldapmodify -Y EXTERNAL -H ldapi:/// -f archivo/confDatabase.ldif

# Insertamos una entrada
ldapmodify -D "cn=admin,o=um,c=es" -W -H ldap://ldap.st.um -f archivo/st.ldif

# Comprobacion de la instalacion mediante una busqeuda
ldapsearch -x  -b "o=um,c=es" correo -H ldap://ldap.st.um




