#!/bin/bash

# Modificar archivos de configuracion pertinentes de Dovecot
#echo -e "disable_plaintext_auth=no\nauth_mechanisms=plain\n!include auth-system.conf.ext" > /etc/dovecot/conf.d/10-auth.conf
#echo -e "mail_location=maildir:~/Maildir" > /etc/dovecot/conf.d/10-mail.conf

cp 10* /etc/dovecot/conf.d
cp -r exim4 /etc

# Crear cuentas en el SO
useradd usuario1 -m
useradd usuario2 -m
passwd usuario1
passwd usuario2

# Reiniciar el servicio
service dovecot restart


# dpkg-reconfigure exim4-config
# *****************************
# tipo de servidor: "internet site"
# Nombre de dominio FQDM: "st.um"
# en blanco -> desde cualquier IP
# Dominios de destino final: "st.um"
# Dominios para reenviar: "st.um; um.es"
# Lista IPs para reenvio incondicional: 10.0.0.0/24
# Limitar consultas DNS: NO
# Formato del buzon: Maildir
# Dividir ficheros de configuracion: NO
# Direcciones para root y admins: "root webmaster@st.um"
