#!/bin/bash

# Modificar archivos de configuracion pertinentes de Dovecot
#echo -e "disable_plaintext_auth=no\nauth_mechanisms=plain\n!include auth-system.conf.ext" > /etc/dovecot/conf.d/10-auth.conf
#echo -e "mail_location=maildir:~/Maildir" > /etc/dovecot/conf.d/10-mail.conf

cp 10* /etc/dovecot/conf.d
cp -r exim4 /etc

# Crear cuentas en el SO
useradd usuario1 -m
useradd usuario2 -m
passwd usuario1
passwd usuario2

# Reiniciar el servicio
service dovecot restart
