#!/bin/bash

interfaz=$1
ip=$2
mascara=$3

echo "Configuración general de red:"

# Preparar interfaz con ip fija para el servidor
echo -e "\t- Desactivar la interfaz $interfaz"
ifconfig $interfaz down

echo -e "\t- Estableciendo ip fija (${ip}) para el servidor, con mascara $mascara (${interfaz})"
ifconfig $interfaz $ip netmask $mascara

# Para IPv6:
# ifconfig $interfaz inet6 add $ip6/64
