#!/bin/bash

# datos:
subred="10.0.0"
mascara="255.255.255.0"

ipservidor="$subred.1"
interfaz="eth2"
interfaz_exterior="eth1"
name="servidor"

ipcliente="$subred.2"
MACcliente="08:11:11:11:11:11"
ipcliente2="$subred.7"
MACcliente2="08:22:22:22:22:22"

dominio="st.um"
# subdominio="st.um"

# Cambia el nombre del host
hostname $name
echo -e "$name" > /etc/hostname

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar parametros de red
# Ejemplo de ejecucion:
# 	./red eth1 192.168.6.1 255.255.255.0
./red $interfaz $ipservidor $mascara &&\

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Instala los paquetes necesarios en el sistema. Sin parametros.
# Ejemplo de ejecucion:
# 	./instalar
./instalar  &&\

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Habilitar funciones de enrutador
# Ejemplo de ejecucion:
# 	./nat eth0 eth1
./nat $interfaz_exterior $interfaz &&\

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Prepara servidor DHCP
./dhcp $subred $mascara $dominio $ipservidor $interfaz $ipcliente $MACcliente $ipcliente2 $MACcliente2

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Pausa necesaria
read -p "Ejecute el script del cliente ahora. Pulse ENTER para continuar..."

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Prepara servidor DNS
# Ejemplo de ejecucion:
./dns $dominio $ipservidor $ipcliente $ipcliente2

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar servicio de correo (SMTP)
# Ejemplo de ejecucion:
# 	./smtp st.um
# ./smtp $subdominio &&\

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar servicio de correo (POP)
# ./pop

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar servidor LDAP
# ./ldap

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar servidor HTTP
# ./http

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Preparar SSL
# ./ssl
