#!/bin/bash
echo "Configurando SSL:"
cp archivo/st-ssl.conf /etc/apache2/sites-available/st

mkdir /etc/apache2/stCA
cp ca/servercert.pem /etc/apache2/stCA
cp ca/serverkey.pem /etc/apache2/stCA
cp ca/cacert.pem /etc/apache2/stCA

# Activa el modulo ssl
a2enmod ssl

/etc/init.d/apache2 restart